main = ".open-next/worker.js"
name = "my-nextjs-app"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true